spring.application.name=api-pokedex
server.port=8081

# Configurações do H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações de Conexão com o Banco em Memória
spring.datasource.url=jdbc:h2:mem:dcbapp
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=testedoluidao

# Otimizações JPA / Hibernate
spring.jpa.open-in-view=false